name: arm-summer-school-2026-dev
channels:
  - conda-forge
dependencies:
  - python=3.11
  - mystmd<1.3.21
  - cookiecutter
  - act-atmos
  - jupyterlab
  - arm_pyart
  - cartopy
  - matplotlib
  - pydda
  - jaxopt
  - tensorflow>=2.6
  - xradar
  - tensorflow-probability>=0.24
  - tobac
